version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: finance_postgres
    environment:
      POSTGRES_DB: financedb
      POSTGRES_USER: financeuser
      POSTGRES_PASSWORD: financepass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U financeuser -d financedb"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: finance_web
    environment:
      - DATABASE_URL=postgresql://financeuser:financepass@postgres:5432/financedb
      - SECRET_KEY=your-secret-key-change-in-production
      - FLASK_ENV=development
    volumes:
      - ./static/uploads:/app/static/uploads
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: finance_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
