version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: finance_postgres
    environment:
      POSTGRES_DB: financedb
      POSTGRES_USER: financeuser
      POSTGRES_PASSWORD: financepass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U financeuser -d financedb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: finance_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    image: prameshwar884/personal-finance-tracker-web:16950058153
    container_name: finance_web
    environment:
      - DATABASE_URL=postgresql://financeuser:financepass@postgres:5432/financedb
      - SECRET_KEY=your-secret-key-change-in-production
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - uploads_data:/app/static/uploads
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  uploads_data:
