apiVersion: v1
kind: Pod
metadata:
  name: ebs-test-pod
  namespace: default
spec:
  containers:
  - name: test-container
    image: nginx
    volumeMounts:
    - name: ebs-storage
      mountPath: /data
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'EBS volume mounted at /data' && df -h /data && sleep 30; done"]
  volumes:
  - name: ebs-storage
    persistentVolumeClaim:
      claimName: ebs-test-pvc


