name: CI/CD

# Exclude the workflow to run on changes to the k8s manifests
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/**'
      - 'README.md'
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-flask

      - name: Test
        run: |
          python -m pytest tests/ -v || echo "Tests completed"

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/personal-finance-tracker-web:${{ github.run_id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-newtag-in-k8s:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update k8s deployment with new image tag
        run: |
          sed -i 's|image: .*/personal-finance-tracker-web:.*|image: '"${{ secrets.DOCKERHUB_USERNAME }}"'/personal-finance-tracker-web:'"${{ github.run_id }}"'|' k8s/app-deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "prameshwar@gmail.com"
          git config --global user.name "Prameshwar"
          git add k8s/app-deployment.yaml
          git commit -m "Update tag in K8s deployment [skip ci]"
          git push